import express from 'express';
import mysql from 'mysql2/promise';
import pg from 'pg';

const { Pool } = pg;

type LegacyEmployeeRow = {
  id: number;
  name: string;
  photo_path: string | null;
  status: string;
  system_key: string | null;
  created_by: number | null;
  created_at: string | null;
  updated_at: string | null;
  deleted_at: string | null;
};

type LegacySaleRow = {
  id: number;
  employee_id: number;
  sale_date: string;
  amount_cents: number;
  xp_points: number;
  note: string | null;
  created_by: number | null;
  created_at: string | null;
  deleted_at: string | null;
  deleted_by: number | null;
};

type LegacySettingRow = {
  setting_key: string;
  setting_value: string | null;
  updated_by: number | null;
  updated_at: string | null;
};

const env = process.env;
const SERVICE_NAME = 'xp';
const SERVICE_VERSION = '0.1.0';
const BASE_PATH = normalizeBasePath(env.BASE_PATH || '/xp');
const PORT = Number.parseInt(env.PORT || '3600', 10);
const LEGACY_MYSQL_IMPORT_ENABLED = normalizeBoolean(env.XP_LEGACY_MYSQL_IMPORT_ENABLED ?? 'true');
const XP_POINTS_PER_THOUSAND_REAIS = 2500;
const XP_FIRST_LEVEL_REQUIREMENT = 30000;

const pgPool = new Pool({
  host: env.POSTGRES_HOST || '127.0.0.1',
  port: Number(env.POSTGRES_PORT || 5432),
  database: env.POSTGRES_DB || 'wimifarma_xp',
  user: env.POSTGRES_USER || 'wimifarma_xp',
  password: env.POSTGRES_PASSWORD || '',
  max: 8,
});

const mysqlPool = LEGACY_MYSQL_IMPORT_ENABLED
  ? mysql.createPool({
      host: env.MYSQL_HOST || '127.0.0.1',
      port: Number(env.MYSQL_PORT || 3306),
      database: env.MYSQL_DATABASE || 'wimifarma_app',
      user: env.MYSQL_USER || 'wimifarma_user',
      password: env.MYSQL_PASSWORD || '',
      waitForConnections: true,
      connectionLimit: 4,
      charset: 'utf8mb4',
      dateStrings: true,
    })
  : null;

const migrationState = {
  employeesImported: 0,
  salesImported: 0,
  settingsImported: 0,
  lastRunAt: null as string | null,
  lastError: null as string | null,
};

const app = express();

function normalizeBasePath(value: string): string {
  const clean = `/${value}`.replace(/\/+/g, '/').replace(/\/$/, '');
  return clean === '' ? '/xp' : clean;
}

function normalizeBoolean(value: unknown): boolean {
  return value === true || value === 1 || value === '1' || value === 'true' || value === 'on';
}

function cleanText(value: unknown, limit: number): string {
  return String(value ?? '').replace(/\s+/g, ' ').trim().slice(0, limit);
}

function validStatus(value: unknown): 'ativo' | 'inativo' {
  return String(value || '').trim() === 'inativo' ? 'inativo' : 'ativo';
}

function pgDateFromMysql(value: string | null | undefined): string | null {
  if (!value) return null;
  const text = String(value).trim();
  if (!text || text === '0000-00-00 00:00:00') return null;
  return text.includes('T') ? text : `${text.replace(' ', 'T')}-03:00`;
}

function mysqlRequired(): mysql.Pool {
  if (!mysqlPool) {
    throw new Error('Legacy MySQL import is disabled.');
  }
  return mysqlPool;
}

async function ensureSchema(): Promise<void> {
  await pgPool.query(`
    CREATE TABLE IF NOT EXISTS xp_employees (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      legacy_mysql_id BIGINT UNIQUE,
      name VARCHAR(180) NOT NULL,
      photo_path VARCHAR(255),
      status TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'inativo')),
      system_key VARCHAR(32) UNIQUE,
      created_by INTEGER,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ,
      deleted_at TIMESTAMPTZ
    )
  `);
  await pgPool.query('CREATE INDEX IF NOT EXISTS xp_employees_status_name_idx ON xp_employees (status, name)');
  await pgPool.query('CREATE INDEX IF NOT EXISTS xp_employees_created_at_idx ON xp_employees (created_at)');
  await pgPool.query(`
    CREATE TABLE IF NOT EXISTS xp_sales (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      legacy_mysql_id BIGINT UNIQUE,
      employee_id BIGINT NOT NULL REFERENCES xp_employees(id) ON UPDATE CASCADE,
      sale_date DATE NOT NULL,
      amount_cents BIGINT NOT NULL CHECK (amount_cents >= 0),
      xp_points BIGINT NOT NULL CHECK (xp_points >= 0),
      note VARCHAR(255),
      created_by INTEGER,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      deleted_at TIMESTAMPTZ,
      deleted_by INTEGER
    )
  `);
  await pgPool.query('CREATE INDEX IF NOT EXISTS xp_sales_employee_date_idx ON xp_sales (employee_id, sale_date)');
  await pgPool.query('CREATE INDEX IF NOT EXISTS xp_sales_date_idx ON xp_sales (sale_date)');
  await pgPool.query('CREATE INDEX IF NOT EXISTS xp_sales_active_date_idx ON xp_sales (deleted_at, sale_date)');
  await pgPool.query('CREATE INDEX IF NOT EXISTS xp_sales_active_employee_date_idx ON xp_sales (deleted_at, employee_id, sale_date)');
  await pgPool.query(`
    CREATE TABLE IF NOT EXISTS xp_settings (
      setting_key VARCHAR(80) PRIMARY KEY,
      setting_value TEXT,
      updated_by INTEGER,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pgPool.query(`
    CREATE TABLE IF NOT EXISTS xp_audit_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      actor_user_id BIGINT,
      action VARCHAR(80) NOT NULL,
      entity_type VARCHAR(80),
      entity_id TEXT,
      summary VARCHAR(255) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pgPool.query('CREATE INDEX IF NOT EXISTS xp_audit_events_created_idx ON xp_audit_events (created_at DESC)');
}

async function migrateLegacyData(): Promise<void> {
  if (!LEGACY_MYSQL_IMPORT_ENABLED) return;
  const startedAt = new Date().toISOString();
  try {
    const mysqlDb = mysqlRequired();
    const [employeeRows] = await mysqlDb.query<mysql.RowDataPacket[]>(
      'SELECT id, name, photo_path, status, system_key, created_by, created_at, updated_at, deleted_at FROM wf_xp_employees ORDER BY id ASC',
    );
    const [saleRows] = await mysqlDb.query<mysql.RowDataPacket[]>(
      'SELECT id, employee_id, sale_date, amount_cents, xp_points, note, created_by, created_at, deleted_at, deleted_by FROM wf_xp_sales ORDER BY id ASC',
    );
    const [settingRows] = await mysqlDb.query<mysql.RowDataPacket[]>(
      'SELECT setting_key, setting_value, updated_by, updated_at FROM wf_xp_settings ORDER BY setting_key ASC',
    );

    const client = await pgPool.connect();
    try {
      await client.query('BEGIN');
      let employeesImported = 0;
      for (const row of employeeRows as LegacyEmployeeRow[]) {
        await client.query(
          `INSERT INTO xp_employees (
             id, legacy_mysql_id, name, photo_path, status, system_key,
             created_by, created_at, updated_at, deleted_at
           ) VALUES (
             $1, $1, $2, $3, $4, $5,
             $6, COALESCE($7::timestamptz, NOW()), $8::timestamptz, $9::timestamptz
           )
           ON CONFLICT (legacy_mysql_id) DO UPDATE SET
             name = EXCLUDED.name,
             photo_path = EXCLUDED.photo_path,
             status = EXCLUDED.status,
             system_key = EXCLUDED.system_key,
             created_by = EXCLUDED.created_by,
             created_at = EXCLUDED.created_at,
             updated_at = EXCLUDED.updated_at,
             deleted_at = EXCLUDED.deleted_at`,
          [
            Number(row.id),
            cleanText(row.name, 180) || 'Funcionario sem nome',
            row.photo_path || null,
            validStatus(row.status),
            row.system_key || null,
            row.created_by ? Number(row.created_by) : null,
            pgDateFromMysql(row.created_at),
            pgDateFromMysql(row.updated_at),
            pgDateFromMysql(row.deleted_at),
          ],
        );
        employeesImported += 1;
      }

      let salesImported = 0;
      for (const row of saleRows as LegacySaleRow[]) {
        await client.query(
          `INSERT INTO xp_sales (
             id, legacy_mysql_id, employee_id, sale_date, amount_cents, xp_points,
             note, created_by, created_at, deleted_at, deleted_by
           ) VALUES (
             $1, $1, $2, $3::date, $4, $5,
             $6, $7, COALESCE($8::timestamptz, NOW()), $9::timestamptz, $10
           )
           ON CONFLICT (legacy_mysql_id) DO UPDATE SET
             employee_id = EXCLUDED.employee_id,
             sale_date = EXCLUDED.sale_date,
             amount_cents = EXCLUDED.amount_cents,
             xp_points = EXCLUDED.xp_points,
             note = EXCLUDED.note,
             created_by = EXCLUDED.created_by,
             created_at = EXCLUDED.created_at,
             deleted_at = EXCLUDED.deleted_at,
             deleted_by = EXCLUDED.deleted_by`,
          [
            Number(row.id),
            Number(row.employee_id),
            row.sale_date,
            Number(row.amount_cents || 0),
            Number(row.xp_points || 0),
            row.note ? cleanText(row.note, 255) : null,
            row.created_by ? Number(row.created_by) : null,
            pgDateFromMysql(row.created_at),
            pgDateFromMysql(row.deleted_at),
            row.deleted_by ? Number(row.deleted_by) : null,
          ],
        );
        salesImported += 1;
      }

      let settingsImported = 0;
      for (const row of settingRows as LegacySettingRow[]) {
        await client.query(
          `INSERT INTO xp_settings (setting_key, setting_value, updated_by, updated_at)
           VALUES ($1, $2, $3, COALESCE($4::timestamptz, NOW()))
           ON CONFLICT (setting_key) DO UPDATE SET
             setting_value = EXCLUDED.setting_value,
             updated_by = EXCLUDED.updated_by,
             updated_at = EXCLUDED.updated_at`,
          [cleanText(row.setting_key, 80), row.setting_value ?? null, row.updated_by ? Number(row.updated_by) : null, pgDateFromMysql(row.updated_at)],
        );
        settingsImported += 1;
      }

      await client.query(`
        SELECT setval(
          pg_get_serial_sequence('xp_employees', 'id'),
          GREATEST((SELECT COALESCE(MAX(id), 1) FROM xp_employees), 1),
          true
        )
      `);
      await client.query(`
        SELECT setval(
          pg_get_serial_sequence('xp_sales', 'id'),
          GREATEST((SELECT COALESCE(MAX(id), 1) FROM xp_sales), 1),
          true
        )
      `);
      await client.query('COMMIT');
      migrationState.employeesImported = employeesImported;
      migrationState.salesImported = salesImported;
      migrationState.settingsImported = settingsImported;
      migrationState.lastRunAt = startedAt;
      migrationState.lastError = null;
    } catch (error) {
      await client.query('ROLLBACK');
      throw error;
    } finally {
      client.release();
    }
  } catch (error) {
    migrationState.lastRunAt = startedAt;
    migrationState.lastError = error instanceof Error ? error.message : String(error);
    console.warn('[xp] legacy migration failed', error);
  }
}

async function postgresStats(): Promise<Record<string, unknown>> {
  const result = await pgPool.query<{
    employees_total: string;
    employees_active: string;
    sales_total: string;
    sales_active: string;
    amount_cents_active: string | null;
    xp_points_active: string | null;
    settings_total: string;
  }>(`
    SELECT
      (SELECT COUNT(*) FROM xp_employees) AS employees_total,
      (SELECT COUNT(*) FROM xp_employees WHERE status = 'ativo' AND deleted_at IS NULL) AS employees_active,
      (SELECT COUNT(*) FROM xp_sales) AS sales_total,
      (SELECT COUNT(*) FROM xp_sales WHERE deleted_at IS NULL) AS sales_active,
      (SELECT COALESCE(SUM(amount_cents), 0) FROM xp_sales WHERE deleted_at IS NULL) AS amount_cents_active,
      (SELECT COALESCE(SUM(xp_points), 0) FROM xp_sales WHERE deleted_at IS NULL) AS xp_points_active,
      (SELECT COUNT(*) FROM xp_settings) AS settings_total
  `);
  return result.rows[0] || {};
}

async function legacyStats(): Promise<Record<string, unknown> | null> {
  if (!LEGACY_MYSQL_IMPORT_ENABLED || !mysqlPool) return null;
  try {
    const [rows] = await mysqlPool.query<mysql.RowDataPacket[]>(`
      SELECT
        (SELECT COUNT(*) FROM wf_xp_employees) AS employees_total,
        (SELECT COUNT(*) FROM wf_xp_employees WHERE status = 'ativo' AND deleted_at IS NULL) AS employees_active,
        (SELECT COUNT(*) FROM wf_xp_sales) AS sales_total,
        (SELECT COUNT(*) FROM wf_xp_sales WHERE deleted_at IS NULL) AS sales_active,
        (SELECT COALESCE(SUM(amount_cents), 0) FROM wf_xp_sales WHERE deleted_at IS NULL) AS amount_cents_active,
        (SELECT COALESCE(SUM(xp_points), 0) FROM wf_xp_sales WHERE deleted_at IS NULL) AS xp_points_active,
        (SELECT COUNT(*) FROM wf_xp_settings) AS settings_total
    `);
    return rows[0] || {};
  } catch (error) {
    return { ok: false, error: error instanceof Error ? error.message : String(error) };
  }
}

app.disable('x-powered-by');
app.set('trust proxy', true);
app.use((_req, res, next) => {
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('X-Frame-Options', 'SAMEORIGIN');
  res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin');
  next();
});

app.get(`${BASE_PATH}/health`, async (_req, res, next) => {
  try {
    await pgPool.query('SELECT 1');
    res.json({
      ok: true,
      service: SERVICE_NAME,
      version: SERVICE_VERSION,
      base_path: BASE_PATH,
      storage: {
        provider: 'postgres',
        database: env.POSTGRES_DB || 'wimifarma_xp',
        legacy_mysql_import_enabled: LEGACY_MYSQL_IMPORT_ENABLED,
        migration: migrationState,
        postgres: await postgresStats(),
        legacy: await legacyStats(),
      },
      rules: {
        xp_per_1000_reais: XP_POINTS_PER_THOUSAND_REAIS,
        first_level_requirement: XP_FIRST_LEVEL_REQUIREMENT,
      },
    });
  } catch (error) {
    next(error);
  }
});

app.get(`${BASE_PATH}/internal/migration-status`, async (_req, res, next) => {
  try {
    res.json({
      ok: true,
      service: SERVICE_NAME,
      migration: migrationState,
      postgres: await postgresStats(),
      legacy: await legacyStats(),
    });
  } catch (error) {
    next(error);
  }
});

app.use((error: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  console.error('[xp] request failed', error);
  res.status(500).json({ ok: false, service: SERVICE_NAME, message: 'XP indisponivel.' });
});

async function withRetry(name: string, fn: () => Promise<unknown>, attempts = 20): Promise<void> {
  let lastError: unknown;
  for (let index = 1; index <= attempts; index += 1) {
    try {
      await fn();
      return;
    } catch (error) {
      lastError = error;
      console.warn(`[xp] waiting for ${name} (${index}/${attempts})`);
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }
  }
  throw lastError;
}

async function start(): Promise<void> {
  await withRetry('postgres', () => pgPool.query('SELECT 1'));
  if (LEGACY_MYSQL_IMPORT_ENABLED) {
    await withRetry('mysql', () => mysqlRequired().query('SELECT 1'));
  }
  await ensureSchema();
  await migrateLegacyData();
  app.listen(PORT, () => {
    console.log(`[xp] listening on ${PORT} at ${BASE_PATH}`);
  });
}

start().catch((error) => {
  console.error('[xp] failed to start', error);
  process.exit(1);
});
