import mysql from 'mysql2/promise';
import { Pool } from 'pg';

type MysqlUserRow = {
  id: number;
  username: string;
  password_hash: string | null;
  role: string | null;
  active: number;
};

type CoreUserRow = {
  id: string;
  legacy_mysql_id: string;
  username: string;
  username_normalized: string;
  password_hash: string | null;
  role: string;
  active: boolean;
};

type ValidationIssue = {
  legacy_mysql_id: number;
  field: string;
  mysql: unknown;
  postgres: unknown;
};

const env = process.env;
const validateOnly = process.argv.includes('--validate-only');
const migrate = process.argv.includes('--migrate') || !validateOnly;

const mysqlPool = mysql.createPool({
  host: env.MYSQL_HOST || '127.0.0.1',
  port: Number(env.MYSQL_PORT || 3306),
  database: env.MYSQL_DATABASE || 'wimifarma_app',
  user: env.MYSQL_USER || 'wimifarma_user',
  password: env.MYSQL_PASSWORD || '',
  waitForConnections: true,
  connectionLimit: 4,
  charset: 'utf8mb4',
  dateStrings: true,
});

const pgPool = new Pool({
  host: env.CORE_POSTGRES_HOST || env.POSTGRES_HOST || '127.0.0.1',
  port: Number(env.CORE_POSTGRES_PORT || env.POSTGRES_PORT || 5432),
  database: env.CORE_POSTGRES_DB || env.POSTGRES_DB || 'wimifarma_core',
  user: env.CORE_POSTGRES_USER || env.POSTGRES_USER || 'wimifarma_core',
  password: env.CORE_POSTGRES_PASSWORD || env.POSTGRES_PASSWORD || '',
  max: 4,
});

function normalizeUsername(value: unknown): string {
  return String(value ?? '').replace(/\s+/g, ' ').trim().toLowerCase();
}

function normalizeRole(value: unknown): string {
  const role = String(value ?? '').replace(/\s+/g, ' ').trim().toLowerCase();
  return role || 'user';
}

function normalizeHash(value: unknown): string | null {
  const hash = String(value ?? '').trim();
  return hash === '' ? null : hash;
}

async function ensureCoreSchema(): Promise<void> {
  await pgPool.query(`
    CREATE TABLE IF NOT EXISTS core_users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      legacy_mysql_id BIGINT NOT NULL UNIQUE,
      username TEXT NOT NULL,
      username_normalized TEXT NOT NULL UNIQUE,
      display_name TEXT NOT NULL DEFAULT '',
      password_hash TEXT,
      role TEXT NOT NULL DEFAULT 'user',
      active BOOLEAN NOT NULL DEFAULT true,
      source TEXT NOT NULL DEFAULT 'mysql:wf_users',
      migrated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pgPool.query(`
    ALTER TABLE core_users
      ADD COLUMN IF NOT EXISTS display_name TEXT NOT NULL DEFAULT ''
  `);
  await pgPool.query(`
    CREATE TABLE IF NOT EXISTS core_audit_logs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      actor_user_id BIGINT REFERENCES core_users(id) ON DELETE SET NULL,
      action TEXT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id TEXT,
      detail TEXT,
      metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pgPool.query(`
    CREATE INDEX IF NOT EXISTS idx_core_audit_logs_created_at
      ON core_audit_logs (created_at DESC)
  `);
  await pgPool.query(`
    CREATE INDEX IF NOT EXISTS idx_core_audit_logs_actor_created
      ON core_audit_logs (actor_user_id, created_at DESC)
  `);
  await pgPool.query(`
    CREATE TABLE IF NOT EXISTS core_login_rate_limits (
      rate_key TEXT PRIMARY KEY,
      username_normalized TEXT,
      ip_hash TEXT,
      attempts_count INTEGER NOT NULL DEFAULT 0,
      window_started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      blocked_until TIMESTAMPTZ,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pgPool.query(`
    CREATE INDEX IF NOT EXISTS idx_core_login_rate_limits_blocked
      ON core_login_rate_limits (blocked_until)
      WHERE blocked_until IS NOT NULL
  `);
}

async function readMysqlUsers(): Promise<MysqlUserRow[]> {
  const [rows] = await mysqlPool.query(
    `SELECT id, username, password_hash, role, active
       FROM wf_users
      ORDER BY id ASC`,
  );
  return (Array.isArray(rows) ? rows : []).map((row) => row as MysqlUserRow);
}

async function assertNoDuplicateUsers(users: MysqlUserRow[]): Promise<void> {
  const byName = new Map<string, number[]>();
  for (const user of users) {
    const normalized = normalizeUsername(user.username);
    if (!normalized) {
      throw new Error(`wf_users id=${user.id} has empty username`);
    }
    byName.set(normalized, [...(byName.get(normalized) || []), user.id]);
  }

  const duplicates = Array.from(byName.entries()).filter(([, ids]) => ids.length > 1);
  if (duplicates.length > 0) {
    throw new Error(`wf_users duplicate usernames: ${duplicates.map(([name, ids]) => `${name}(${ids.join(',')})`).join('; ')}`);
  }
}

async function migrateUsers(users: MysqlUserRow[]): Promise<number> {
  let migrated = 0;
  const client = await pgPool.connect();
  try {
    await client.query('BEGIN');
    for (const user of users) {
      const username = String(user.username || '').trim();
      const normalized = normalizeUsername(username);
      const passwordHash = normalizeHash(user.password_hash);
      const role = normalizeRole(user.role);
      const active = Number(user.active) === 1;
      await client.query(
        `INSERT INTO core_users (
           id, legacy_mysql_id, username, username_normalized,
           password_hash, role, active, updated_at, migrated_at
         ) VALUES (
           $1, $1, $2, $3,
           $4, $5, $6, NOW(), NOW()
         )
         ON CONFLICT (legacy_mysql_id) DO UPDATE SET
           username = EXCLUDED.username,
           username_normalized = EXCLUDED.username_normalized,
           password_hash = EXCLUDED.password_hash,
           role = EXCLUDED.role,
           active = EXCLUDED.active,
           updated_at = NOW(),
           migrated_at = NOW()`,
        [user.id, username, normalized, passwordHash, role, active],
      );
      migrated += 1;
    }
    await client.query(`
      SELECT setval(
        pg_get_serial_sequence('core_users', 'id'),
        GREATEST((SELECT COALESCE(MAX(id), 1) FROM core_users), 1),
        true
      )
    `);
    await client.query('COMMIT');
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
  return migrated;
}

async function readCoreUsers(): Promise<Map<number, CoreUserRow>> {
  const result = await pgPool.query<CoreUserRow>(
    `SELECT id::text, legacy_mysql_id::text, username, username_normalized,
            password_hash, role, active
       FROM core_users`,
  );
  const rows = new Map<number, CoreUserRow>();
  for (const row of result.rows) {
    rows.set(Number(row.legacy_mysql_id), row);
  }
  return rows;
}

async function validateUsers(users: MysqlUserRow[]): Promise<{ issues: ValidationIssue[]; coreCount: number }> {
  const coreUsers = await readCoreUsers();
  const issues: ValidationIssue[] = [];

  for (const user of users) {
    const core = coreUsers.get(Number(user.id));
    if (!core) {
      issues.push({ legacy_mysql_id: user.id, field: 'missing', mysql: 'present', postgres: 'missing' });
      continue;
    }
    const expected = {
      id: String(user.id),
      username: String(user.username || '').trim(),
      username_normalized: normalizeUsername(user.username),
      password_hash: normalizeHash(user.password_hash),
      role: normalizeRole(user.role),
      active: Number(user.active) === 1,
    };
    const actual = {
      id: core.id,
      username: core.username,
      username_normalized: core.username_normalized,
      password_hash: core.password_hash,
      role: core.role,
      active: core.active,
    };

    for (const field of Object.keys(expected) as Array<keyof typeof expected>) {
      if (expected[field] !== actual[field]) {
        issues.push({
          legacy_mysql_id: user.id,
          field,
          mysql: expected[field],
          postgres: actual[field],
        });
      }
    }
  }

  return { issues, coreCount: coreUsers.size };
}

async function main(): Promise<void> {
  await ensureCoreSchema();
  const users = await readMysqlUsers();
  await assertNoDuplicateUsers(users);

  let migrated = 0;
  if (migrate) {
    migrated = await migrateUsers(users);
  }

  const validation = await validateUsers(users);
  const summary = {
    ok: validation.issues.length === 0 && validation.coreCount >= users.length,
    mode: validateOnly ? 'validate' : 'migrate',
    mysql_users: users.length,
    core_users: validation.coreCount,
    migrated_users: migrated,
    issues: validation.issues.slice(0, 20),
  };

  console.log(JSON.stringify(summary, null, 2));
  if (!summary.ok) {
    process.exitCode = 1;
  }
}

main()
  .catch((error: unknown) => {
    console.error(JSON.stringify({
      ok: false,
      error: error instanceof Error ? error.message : String(error),
    }, null, 2));
    process.exitCode = 1;
  })
  .finally(async () => {
    await Promise.allSettled([mysqlPool.end(), pgPool.end()]);
  });
